@startuml
'https://plantuml.com/sequence-diagram

class App {
    + main()
    + start()
}

class ListController {
    + newToDoListButtonClicked(): add new to do list
    + deleteListsButtonClicked(): remove an existing to do list
    + saveListsButtonClicked(): save all items in all to do lists to external storage
    + loadListsButtonClicked():
        + loadSingleToDoListButtonClicked(): load single to do list from external storage
        + loadToDoListsButtonClicked(): load multiple to do lists
}

class ToDoListController {
    + newTaskButtonClicked(): add new item to existing to do list
    + deleteItemsButtonClicked(): remove item from existing to do list
    + taskCompletedCheckBoxClicked(): mark an item in a to do list as complete
    + displayButtonClicked():
        + displayAllItemsButtonClicked(): display all existing items
        + displayIncompleteItemsButtonClicked(): display only the incompleted items
        + displayCompletedItemsButtonClicked(): display completed items
    + sortByDateButtonClicked(): sort items by due date
    + titleTextBoxClicked(): edit the title of existing to do list
    + saveItemsButtonClicked(): save all items in a single to do list to external storage
}

class TaskController {
    + descriptionTextBoxClicked(): edit description of an item within an existing to do list
    + calendarClicked(): edit the due date of an item within an existing to do list
}

javafx.Application <|- App
App -- ListController
ListController *-> ToDoListController
ToDoListController *-> TaskController

@enduml